//ABRIR OPERACIÓN ALZA
{
    "name": "sendMessage",
    "request_id": "1502",
    "local_time": 1332260,
    "msg": {
        "name": "place-order-temp",
        "version": "4.0",
        "body": {
            "user_balance_id": 200797948,
            "client_platform_id": 9,
            "instrument_type": "forex",
            "instrument_id": "EURUSD",
            "side": "buy",
            "type": "market",
            "amount": "1",
            "leverage": 200,
            "limit_price": 0,
            "stop_price": 0,
            "auto_margin_call": true,
            "use_trail_stop": false
        }
    }
}

//ABRIR OPERACIÓN BAJA
{
    "name": "sendMessage",
    "request_id": "1547",
    "local_time": 1368963,
    "msg": {
        "name": "place-order-temp",
        "version": "4.0",
        "body": {
            "user_balance_id": 200797948,
            "client_platform_id": 9,
            "instrument_type": "forex",
            "instrument_id": "EURUSD",
            "side": "sell",
            "type": "market",
            "amount": "1",
            "leverage": 200,
            "limit_price": 0,
            "stop_price": 0,
            "auto_margin_call": true,
            "use_trail_stop": false
        }
    }
}




//DATOS DE LLEGADA DE OPERACIÓN ALZA
{
    "name": "position-changed",
    "microserviceName": "portfolio",
    "msg": {
        "raw_event": {
            "trading_position_changed1": {
                "last_change_reason": "market_order",
                "instrument_id_escape": "EURUSD",
                "instrument_strike_value": null,
                "instrument_type": "forex",
                "instrument_id": "EURUSD",
                "instrument_underlying": "EURUSD",
                "instrument_active_id": 1,
                "instrument_expiration": null,
                "instrument_strike": null,
                "instrument_dir": null,
                "instrument_period": null,
                "instrument_percent": null,
                "id": 1125667255,
                "user_id": 47421726,
                "user_balance_id": 226446523,
                "user_balance_type": 4,
                "create_at": 1618293811214,
                "update_at": 1618293811214,
                "close_at": null,
                "type": "long",
                "leverage": 200,
                "count": 8408.378,
                "count_realized": 0,
                "status": "open",
                "buy_amount": 9999.999872,
                "sell_amount": 0,
                "buy_amount_enrolled": 9999.999872,
                "sell_amount_enrolled": 0,
                "commission_amount": 0,
                "commission": 0,
                "commission_enrolled": 0,
                "close_effect_amount": null,
                "close_effect_amount_enrolled": null,
                "close_reason": null,
                "close_underlying_price": null,
                "open_underlying_price": 1.18929,
                "pnl_realized": 0,
                "pnl_realized_enrolled": 0,
                "buy_avg_price": 1.18929,
                "buy_avg_price_enrolled": 1.18929,
                "sell_avg_price": 0,
                "sell_avg_price_enrolled": 0,
                "stop_lose_order_id": null,
                "take_profit_order_id": null,
                "tpsl_extra": null,
                "currency": "USD",
                "margin": 49.999999,
                "margin_call": 0,
                "margin_call_enrolled": 0,
                "swap": 0,
                "swap_enrolled": 0,
                "custodial": 0,
                "custodial_enrolled": 0,
                "custodial_last_age": 0,
                "user_group_id": 193,
                "charge": 0,
                "charge_enrolled": 0,
                "orders": [],
                "currency_unit": 1,
                "currency_rate": 1,
                "open_client_platform_id": 2,
                "extra_data": {
                    "amount": 50000000,
                    "version": "4.0",
                    "init_time": 1618293811101,
                    "use_trail_stop": false,
                    "auto_margin_call": true,
                    "last_change_reason": "market_order",
                    "stop_out_threshold": 95,
                    "use_token_for_commission": false
                },
                "order_ids": [
                    2522431783
                ],
                "last_index": 24565635532,
                "open_quote_final_ask": 1.18929,
                "open_quote_final_bid": 1.18919,
                "index": 24565635532
            }
        },
        "version": 32227291018,
        "id": "10f73def54a245e56a59f800455fa70e",
        "user_id": 47421726,
        "user_balance_id": 226446523,
        "platform_id": 2,
        "external_id": 1125667255,
        "active_id": 1,
        "instrument_id": "1",
        "source": "trading",
        "instrument_type": "forex",
        "status": "open",
        "open_time": 1618293811214,
        "open_quote": 1.18929,
        "invest": 49.999999360000004,
        "invest_enrolled": 49.999999360000004,
        "sell_profit": 49.15916156000009,
        "sell_profit_enrolled": 49.15916156000009,
        "expected_profit": 0,
        "expected_profit_enrolled": 0,
        "pnl": -0.8408377999999075,
        "pnl_net": -0.8408377999999075,
        "current_price": 1.18919,
        "quote_timestamp": 1618293811000,
        "swap": 0
    }
}

{
    "name": "position-changed",
    "microserviceName": "portfolio",
    "msg": {
        "raw_event": {
            "trading_position_changed1": {
                "id": 1125667255,
                "swap": 0,
                "type": "long",
                "count": 8408.378,
                "index": 24565635532,
                "charge": 0,
                "margin": 49.999999,
                "orders": [],
                "status": "open",
                "user_id": 47421726,
                "close_at": null,
                "currency": "USD",
                "leverage": 200,
                "create_at": 1618293811214,
                "custodial": 0,
                "order_ids": [
                    2522431783
                ],
                "update_at": 1618293811214,
                "buy_amount": 9999.999872,
                "commission": 0,
                "extra_data": {
                    "amount": 50000000,
                    "version": "4.0",
                    "init_time": 1618293811101,
                    "use_trail_stop": false,
                    "auto_margin_call": true,
                    "last_change_reason": "market_order",
                    "stop_out_threshold": 95,
                    "use_token_for_commission": false
                },
                "last_index": 24565635532,
                "tpsl_extra": null,
                "margin_call": 0,
                "sell_amount": 0,
                "close_reason": null,
                "pnl_realized": 0,
                "buy_avg_price": 1.18929,
                "currency_rate": 1,
                "currency_unit": 1,
                "instrument_id": "EURUSD",
                "swap_enrolled": 0,
                "user_group_id": 193,
                "count_realized": 0,
                "instrument_dir": null,
                "sell_avg_price": 0,
                "charge_enrolled": 0,
                "instrument_type": "forex",
                "user_balance_id": 226446523,
                "commission_amount": 0,
                "instrument_period": null,
                "instrument_strike": null,
                "user_balance_type": 4,
                "custodial_enrolled": 0,
                "custodial_last_age": 0,
                "instrument_percent": null,
                "last_change_reason": "market_order",
                "stop_lose_order_id": null,
                "buy_amount_enrolled": 9999.999872,
                "close_effect_amount": null,
                "commission_enrolled": 0,
                "instrument_active_id": 1,
                "instrument_id_escape": "EURUSD",
                "margin_call_enrolled": 0,
                "open_quote_final_ask": 1.18929,
                "open_quote_final_bid": 1.18919,
                "sell_amount_enrolled": 0,
                "take_profit_order_id": null,
                "instrument_expiration": null,
                "instrument_underlying": "EURUSD",
                "open_underlying_price": 1.18929,
                "pnl_realized_enrolled": 0,
                "buy_avg_price_enrolled": 1.18929,
                "close_underlying_price": null,
                "instrument_strike_value": null,
                "open_client_platform_id": 2,
                "sell_avg_price_enrolled": 0,
                "close_effect_amount_enrolled": null
            }
        },
        "version": 32227291020,
        "id": "10f73def54a245e56a59f800455fa70e",
        "user_id": 47421726,
        "user_balance_id": 226446523,
        "platform_id": 2,
        "external_id": 1125667255,
        "active_id": 1,
        "instrument_id": "1",
        "source": "trading",
        "instrument_type": "forex",
        "status": "open",
        "open_time": 1618293811214,
        "open_quote": 1.18929,
        "invest": 49.99999936,
        "invest_enrolled": 49.99999936,
        "sell_profit": 49.159161560000086,
        "sell_profit_enrolled": 49.159161560000086,
        "expected_profit": 0,
        "expected_profit_enrolled": 0,
        "pnl": -0.8408377999999075,
        "pnl_net": -0.8408377999999075,
        "current_price": 1.18919,
        "quote_timestamp": 1618293811000,
        "swap": 0
    }
}

//DATOS DE LLEGADA DE OPERACIÓN CERRADA ALZA
{
    "name": "position-changed",
    "microserviceName": "portfolio",
    "msg": {
        "raw_event": {
            "trading_position_changed1": {
                "last_change_reason": "market_order",
                "instrument_id_escape": "EURUSD",
                "instrument_strike_value": null,
                "instrument_type": "forex",
                "instrument_id": "EURUSD",
                "instrument_underlying": "EURUSD",
                "instrument_active_id": 1,
                "instrument_expiration": null,
                "instrument_strike": null,
                "instrument_dir": null,
                "instrument_period": null,
                "instrument_percent": null,
                "id": 1125667255,
                "user_id": 47421726,
                "user_balance_id": 226446523,
                "user_balance_type": 4,
                "create_at": 1618293811214,
                "update_at": 1618293955922,
                "close_at": 1618293955922,
                "type": "long",
                "leverage": 200,
                "count": 0,
                "count_realized": 8408.378,
                "status": "closed",
                "buy_amount": 9999.999872,
                "sell_amount": 10000.924793,
                "buy_amount_enrolled": 9999.999872,
                "sell_amount_enrolled": 10000.924793,
                "commission_amount": 0,
                "commission": 0,
                "commission_enrolled": 0,
                "close_effect_amount": 0,
                "close_effect_amount_enrolled": 0,
                "close_reason": "default",
                "close_underlying_price": 1.1894,
                "open_underlying_price": 1.18929,
                "pnl_realized": 0.924922,
                "pnl_realized_enrolled": 0.924922,
                "buy_avg_price": 1.18929,
                "buy_avg_price_enrolled": 1.18929,
                "sell_avg_price": 1.1894,
                "sell_avg_price_enrolled": 1.1894,
                "stop_lose_order_id": null,
                "take_profit_order_id": null,
                "tpsl_extra": null,
                "currency": "USD",
                "margin": 0,
                "margin_call": 0,
                "margin_call_enrolled": 0,
                "swap": 0,
                "swap_enrolled": 0,
                "custodial": 0,
                "custodial_enrolled": 0,
                "custodial_last_age": 0,
                "user_group_id": 193,
                "charge": 0,
                "charge_enrolled": 0,
                "orders": [],
                "currency_unit": 1,
                "currency_rate": 1,
                "open_client_platform_id": 2,
                "extra_data": {
                    "amount": 50000000,
                    "version": "4.0",
                    "init_time": "1618293955808",
                    "use_trail_stop": false,
                    "auto_margin_call": true,
                    "last_change_reason": "market_order",
                    "stop_out_threshold": 95,
                    "use_token_for_commission": false
                },
                "order_ids": [
                    2522435251,
                    2522431783
                ],
                "last_index": 24565690437,
                "open_quote_final_ask": 1.18929,
                "open_quote_final_bid": 1.18919,
                "index": 24565690437
            }
        },
        "version": 32227377680,
        "id": "10f73def54a245e56a59f800455fa70e",
        "user_id": 47421726,
        "user_balance_id": 226446523,
        "platform_id": 2,
        "external_id": 1125667255,
        "active_id": 1,
        "instrument_id": "1",
        "source": "trading",
        "instrument_type": "forex",
        "status": "closed",
        "open_time": 1618293811214,
        "open_quote": 1.18929,
        "invest": 49.999999358100006,
        "invest_enrolled": 49.999999358100006,
        "close_quote": 1.1894,
        "close_reason": "default",
        "close_time": 1618293955922,
        "close_profit": 50.92492135810001,
        "close_profit_enrolled": 50.92492135810001,
        "pnl": 0.924922,
        "pnl_realized": 0.924922,
        "pnl_net": 0.924922,
        "swap": 0
    }
}





//DATOS DE LLEGADA DE OPERACIÓN BAJA
{
    "name": "position-changed",
    "microserviceName": "portfolio",
    "msg": {
        "raw_event": {
            "trading_position_changed1": {
                "last_change_reason": "market_order",
                "instrument_id_escape": "EURUSD",
                "instrument_strike_value": null,
                "instrument_type": "forex",
                "instrument_id": "EURUSD",
                "instrument_underlying": "EURUSD",
                "instrument_active_id": 1,
                "instrument_expiration": null,
                "instrument_strike": null,
                "instrument_dir": null,
                "instrument_period": null,
                "instrument_percent": null,
                "id": 1125668540,
                "user_id": 47421726,
                "user_balance_id": 226446523,
                "user_balance_type": 4,
                "create_at": 1618294003145,
                "update_at": 1618294003145,
                "close_at": null,
                "type": "short",
                "leverage": 200,
                "count": -8407.459,
                "count_realized": 0,
                "status": "open",
                "buy_amount": 0,
                "sell_amount": 9999.999884,
                "buy_amount_enrolled": 0,
                "sell_amount_enrolled": 9999.999884,
                "commission_amount": 0,
                "commission": 0,
                "commission_enrolled": 0,
                "close_effect_amount": null,
                "close_effect_amount_enrolled": null,
                "close_reason": null,
                "close_underlying_price": null,
                "open_underlying_price": 1.18942,
                "pnl_realized": 0,
                "pnl_realized_enrolled": 0,
                "buy_avg_price": 0,
                "buy_avg_price_enrolled": 0,
                "sell_avg_price": 1.18942,
                "sell_avg_price_enrolled": 1.18942,
                "stop_lose_order_id": null,
                "take_profit_order_id": null,
                "tpsl_extra": null,
                "currency": "USD",
                "margin": 49.999999,
                "margin_call": 0,
                "margin_call_enrolled": 0,
                "swap": 0,
                "swap_enrolled": 0,
                "custodial": 0,
                "custodial_enrolled": 0,
                "custodial_last_age": 0,
                "user_group_id": 193,
                "charge": 0,
                "charge_enrolled": 0,
                "orders": [],
                "currency_unit": 1,
                "currency_rate": 1,
                "open_client_platform_id": 2,
                "extra_data": {
                    "amount": 50000000,
                    "version": "4.0",
                    "init_time": 1618294002991,
                    "use_trail_stop": false,
                    "auto_margin_call": true,
                    "last_change_reason": "market_order",
                    "stop_out_threshold": 95,
                    "use_token_for_commission": false
                },
                "order_ids": [
                    2522436088
                ],
                "last_index": 24565709478,
                "open_quote_final_ask": 1.18952,
                "open_quote_final_bid": 1.18942,
                "index": 24565709478
            }
        },
        "version": 32227409241,
        "id": "66dd103686779030bf8c2dd5908a72db",
        "user_id": 47421726,
        "user_balance_id": 226446523,
        "platform_id": 2,
        "external_id": 1125668540,
        "active_id": 1,
        "instrument_id": "1",
        "source": "trading",
        "instrument_type": "forex",
        "status": "open",
        "open_time": 1618294003145,
        "open_quote": 1.18942,
        "invest": 49.99999942,
        "invest_enrolled": 49.99999942,
        "sell_profit": 49.15925352000009,
        "sell_profit_enrolled": 49.15925352000009,
        "expected_profit": 0,
        "expected_profit_enrolled": 0,
        "pnl": -0.8407458999999075,
        "pnl_net": -0.8407458999999075,
        "current_price": 1.18952,
        "quote_timestamp": 1618294003000,
        "swap": 0
    }
}

{
    "name": "position-changed",
    "microserviceName": "portfolio",
    "msg": {
        "raw_event": {
            "trading_position_changed1": {
                "id": 1125668540,
                "swap": 0,
                "type": "short",
                "count": -8407.459,
                "index": 24565709478,
                "charge": 0,
                "margin": 49.999999,
                "orders": [],
                "status": "open",
                "user_id": 47421726,
                "close_at": null,
                "currency": "USD",
                "leverage": 200,
                "create_at": 1618294003145,
                "custodial": 0,
                "order_ids": [
                    2522436088
                ],
                "update_at": 1618294003145,
                "buy_amount": 0,
                "commission": 0,
                "extra_data": {
                    "amount": 50000000,
                    "version": "4.0",
                    "init_time": 1618294002991,
                    "use_trail_stop": false,
                    "auto_margin_call": true,
                    "last_change_reason": "market_order",
                    "stop_out_threshold": 95,
                    "use_token_for_commission": false
                },
                "last_index": 24565709478,
                "tpsl_extra": null,
                "margin_call": 0,
                "sell_amount": 9999.999884,
                "close_reason": null,
                "pnl_realized": 0,
                "buy_avg_price": 0,
                "currency_rate": 1,
                "currency_unit": 1,
                "instrument_id": "EURUSD",
                "swap_enrolled": 0,
                "user_group_id": 193,
                "count_realized": 0,
                "instrument_dir": null,
                "sell_avg_price": 1.18942,
                "charge_enrolled": 0,
                "instrument_type": "forex",
                "user_balance_id": 226446523,
                "commission_amount": 0,
                "instrument_period": null,
                "instrument_strike": null,
                "user_balance_type": 4,
                "custodial_enrolled": 0,
                "custodial_last_age": 0,
                "instrument_percent": null,
                "last_change_reason": "market_order",
                "stop_lose_order_id": null,
                "buy_amount_enrolled": 0,
                "close_effect_amount": null,
                "commission_enrolled": 0,
                "instrument_active_id": 1,
                "instrument_id_escape": "EURUSD",
                "margin_call_enrolled": 0,
                "open_quote_final_ask": 1.18952,
                "open_quote_final_bid": 1.18942,
                "sell_amount_enrolled": 9999.999884,
                "take_profit_order_id": null,
                "instrument_expiration": null,
                "instrument_underlying": "EURUSD",
                "open_underlying_price": 1.18942,
                "pnl_realized_enrolled": 0,
                "buy_avg_price_enrolled": 0,
                "close_underlying_price": null,
                "instrument_strike_value": null,
                "open_client_platform_id": 2,
                "sell_avg_price_enrolled": 1.18942,
                "close_effect_amount_enrolled": null
            }
        },
        "version": 32227409242,
        "id": "66dd103686779030bf8c2dd5908a72db",
        "user_id": 47421726,
        "user_balance_id": 226446523,
        "platform_id": 2,
        "external_id": 1125668540,
        "active_id": 1,
        "instrument_id": "1",
        "source": "trading",
        "instrument_type": "forex",
        "status": "open",
        "open_time": 1618294003145,
        "open_quote": 1.18942,
        "invest": 49.99999942,
        "invest_enrolled": 49.99999942,
        "sell_profit": 49.15925352000009,
        "sell_profit_enrolled": 49.15925352000009,
        "expected_profit": 0,
        "expected_profit_enrolled": 0,
        "pnl": -0.8407458999999075,
        "pnl_net": -0.8407458999999075,
        "current_price": 1.18952,
        "quote_timestamp": 1618294003000,
        "swap": 0
    }
}

//DATOS DE LLEGADA DE OPERACIÓN CERRADA BAJA
{
    "name": "position-changed",
    "microserviceName": "portfolio",
    "msg": {
        "raw_event": {
            "trading_position_changed1": {
                "last_change_reason": "market_order",
                "instrument_id_escape": "EURUSD",
                "instrument_strike_value": null,
                "instrument_type": "forex",
                "instrument_id": "EURUSD",
                "instrument_underlying": "EURUSD",
                "instrument_active_id": 1,
                "instrument_expiration": null,
                "instrument_strike": null,
                "instrument_dir": null,
                "instrument_period": null,
                "instrument_percent": null,
                "id": 1125668540,
                "user_id": 47421726,
                "user_balance_id": 226446523,
                "user_balance_type": 4,
                "create_at": 1618294003145,
                "update_at": 1618294032863,
                "close_at": 1618294032863,
                "type": "short",
                "leverage": 200,
                "count": 0,
                "count_realized": 8407.459,
                "status": "closed",
                "buy_amount": 10000.672481,
                "sell_amount": 9999.999884,
                "buy_amount_enrolled": 10000.672481,
                "sell_amount_enrolled": 9999.999884,
                "commission_amount": 0,
                "commission": 0,
                "commission_enrolled": 0,
                "close_effect_amount": 0,
                "close_effect_amount_enrolled": 0,
                "close_reason": "default",
                "close_underlying_price": 1.1895,
                "open_underlying_price": 1.18942,
                "pnl_realized": -0.672597,
                "pnl_realized_enrolled": -0.672597,
                "buy_avg_price": 1.1895,
                "buy_avg_price_enrolled": 1.1895,
                "sell_avg_price": 1.18942,
                "sell_avg_price_enrolled": 1.18942,
                "stop_lose_order_id": null,
                "take_profit_order_id": null,
                "tpsl_extra": null,
                "currency": "USD",
                "margin": 0,
                "margin_call": 0,
                "margin_call_enrolled": 0,
                "swap": 0,
                "swap_enrolled": 0,
                "custodial": 0,
                "custodial_enrolled": 0,
                "custodial_last_age": 0,
                "user_group_id": 193,
                "charge": 0,
                "charge_enrolled": 0,
                "orders": [],
                "currency_unit": 1,
                "currency_rate": 1,
                "open_client_platform_id": 2,
                "extra_data": {
                    "amount": 50000000,
                    "version": "4.0",
                    "init_time": "1618294032744",
                    "use_trail_stop": false,
                    "auto_margin_call": true,
                    "last_change_reason": "market_order",
                    "stop_out_threshold": 95,
                    "use_token_for_commission": false
                },
                "order_ids": [
                    2522436576,
                    2522436088
                ],
                "last_index": 24565717078,
                "open_quote_final_ask": 1.18952,
                "open_quote_final_bid": 1.18942,
                "index": 24565717078
            }
        },
        "version": 32227424842,
        "id": "66dd103686779030bf8c2dd5908a72db",
        "user_id": 47421726,
        "user_balance_id": 226446523,
        "platform_id": 2,
        "external_id": 1125668540,
        "active_id": 1,
        "instrument_id": "1",
        "source": "trading",
        "instrument_type": "forex",
        "status": "closed",
        "open_time": 1618294003145,
        "open_quote": 1.18942,
        "invest": 49.999999418899996,
        "invest_enrolled": 49.999999418899996,
        "close_quote": 1.1895,
        "close_reason": "default",
        "close_time": 1618294032863,
        "close_profit": 49.32740241889999,
        "close_profit_enrolled": 49.32740241889999,
        "pnl": -0.672597,
        "pnl_realized": -0.672597,
        "pnl_net": -0.672597,
        "swap": 0
    }
}